### ISSUE TITLE
update Vega README

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/STAT210-Wistariahurst#2]
@annajzhou can you please augment my placeholder text at https://github.com/STAT210-S23/STAT210-Wistariahurst/blob/main/Vega_Newsletters/README.md? 

This file should mention that a report will be posted here as well and give a roadmap to the project, scans, and transcriptions.

I suspect that much of this can be copied and lightly edited from your private repo.

**Comment by annajzhou** [comment]
Yes, done.

**Comment by nicholasjhorton** [comment]
Done via https://github.com/STAT210-S23/STAT210-Wistariahurst/commit/9d64369cb1b5b38285ed1de8f1b649f583a8c14b
