### ISSUE TITLE
what Nick should copy

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/STAT210-Wistariahurst#3]
@sedelson31 can you please alert Nick to what should be copied (and where) from your private repo to https://github.com/STAT210-S23/STAT210-Wistariahurst/tree/main/Bachelder_Letters? 

I will be announcing this public repo at the presentations tomorrow and would like it to include the scans and the transcriptions.

Thanks in advance, Nick

**Comment by sedelson31** [comment]
The `transcription_process` folder, the `scans_processed_pdfs` folder, the `scans_original` folder, the `transcriptions` folder and the `report` folder (and the READ.md of course)

**Comment by nicholasjhorton** [comment]
@sedelson31 before I copy these can you please ensure that there are short, descriptive README.md files in each of the first four folders that you mentioned? 

I will hold off copying the files until I hear from you.

And I will hold off copying the report for now.

**Comment by sedelson31** [comment]
Done. Also please copy the `scans_processed_images` folder.

**Comment by sedelson31** [comment]
Trying to push - keep getting an error that my "remote disconnected"

**Comment by nicholasjhorton** [comment]
Done. Can you please let me know if you see any issues?
