### ISSUE TITLE
stub out README for the Bachelder project

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/STAT210-Wistariahurst#4]
@sedelson31 can you please stub out and update https://github.com/STAT210-S23/STAT210-Wistariahurst/blob/main/Bachelder_Letters/README.md for the overview/roadmap for these project materials? I suspect that you can copy this from what you've done earlier. This will be needed today if at all possible.

Can you please tag @LorraineOloo when you push your changes so that she and I can review? Thanks in advance, Nick

**Comment by nicholasjhorton** [comment]
@LorraineOloo will also want to review the plan (and my implementation of it) for #3

**Comment by LorraineOloo** [comment]
@sedelson31 can you please help me out with this?

**Comment by sedelson31** [comment]
Just pushed.

**Comment by nicholasjhorton** [comment]
Done via https://github.com/STAT210-S23/STAT210-Wistariahurst/commit/5cbd1820494c51ff359b33d7db42284248591f78, thanks!
